@extends('layout')
@section('content')
    <h1>Meet Our Team</h1>
<div id="profiles" class="profiles">
    <p>Our staff draws from a range of experience in real estate, allowing you to complete even the most complicated settlements with confidence. Our range of title and closing services includes title searches, title examinations, title insurance, closing cost estimations, escrow services, residential closing services and commercial closing services.
    </p>
    <div class="my-3">
        <b>Debra B. Adler, Esq., Vice President/Commercial Counsel</b>, joined Residential Title & Escrow Company/Commercial Settlement Services, LLC in April of 2019. She has been a practicing attorney for over 30 years. She is admitted to the Bar in Maryland and the District of Columbia, and is a licensed title producer in Maryland. Ms. Adler earned her undergraduate degree from the University of Maryland, College Park and her Juris Doctor degree from the University of Baltimore School of Law. After a one-year judicial clerkship, she spent 3 years as an associate at Smith, Somerville & Case before joining the firm of Resnick, Eidelberg & Jack, P.A. (“RE&J”) in 1992. Ms. Adler spent 10 years at RE&J representing institutional clients in commercial real estate finance and related transactions, including foreclosures and bankruptcy matters. In 2002, she founded her own firm, Jack & Adler where she continued her quality long-term representation of institutional lenders. In 2011, Ms. Adler continued her law practice as Managing Partner of The Sopher Adler Group and currently as the Law Offices of Debra B. Adler. Ms. Adler has extensive experience in commercial title review and settlement transactions.
    </div>
    <div class="my-3">
        <b>Suzanne Akehurst, Accounting Representative</b>, has been with Residential Title & Escrow Company since 2006. She previously worked for a large national bank and reconciled multi-million dollar accounts for over 35 years. Sue is extremely detail oriented and prides herself on her meticulous work. Sue lives in Middle River with her husband and enjoys spending time with her kids and grandchildren.
    </div>
    <div class="my-3">
        <b>Kim Apperson, Settlement Officer</b>, graduated from the University of Baltimore with a Bachelor’s degree in Business Administration. After college, she worked for a large home builder as a settlement and sales administrator. She later went on to work for several banks and mortgage companies and held positions as loan originator, underwriter, processor and closer. She has over 30 years’ experience in the real estate and finance industry. Kim joined the Residential team in 2018 as a Settlement Officer. She has lived in the Bowley’s Quarters area for the past 35 years with her daughter.
    </div>
    <div class="my-3">
        <b>Cindy Barber, Vice President</b>, received her Bachelor’s degree in Business Admin. from Towson University. She oversees the daily operations of our residential department and conducts numerous closings. Her 35+ years experience in the title industry brings an extensive array of knowledge to her duties reviewing titles, judgments and liens and managing the daily operations of our processing and settlement departments. A native Baltimorean, Cindy lives in Timonium and loves to travel, shop and spend time with her family.
    </div>
    <div class="my-3">
        <b>Judy Borns, Account Executive</b>, is a graduate of the University of Dayton with a BS in elementary education. Judy oversees the Marketing team’s efforts and directs the Company’s various marketing initiatives and special events, always doing “Whatever It Takes” for our customers. She served for 20 years as a Marketing and Sales Director with several leading homebuilders in the region prior to joining Residential Title & Escrow. Judy initially began her professional career as an early childhood educator and as a reading specialist before relocating to Maryland in 1972 and beginning a new career in the Real Estate industry. She is a member of HCAR, GBBR, SMC and sits on the Harford County Board of MBIA and the Builders Care Foundation. Judy lives in Harford County and spends most of her time with her 4 beautiful children and 11 amazing grandchildren.
    </div>
    <div class="my-3">
        <b>Larry Brenner, Chief Financial Officer</b>, is a Baltimore native and experienced financial professional in the real estate industry. A University of Baltimore graduate, he spent the first 30 years of his career in real estate development with well-established players in the area. Larry is responsible for all aspects of financial management, as well as office management and human resources. When he’s not working, he spends lots of time with his grandson, skiing, and working around the house.
    </div>
    <div class="my-3">
        <b>Lauren Daniels, Commercial Post Closer</b>, joins us with over 20 years of experience in post-closing and processing. She specializes in title policies, recordings and releases. Lauren currently lives in Nottingham, MD and enjoys spending time with her family.
    </div>
    <div class="my-3">
        <b>Terry Anne Hearn, Vice President</b>, Business Development, graduated from Mount Saint Mary’s University with a BS in Business Finance. Terry Anne is a seasoned professional with commercial real estate industry experience both locally and globally. Before joining Residential Title & Escrow in 2011, Terry Anne spent two years as the Director of Business Development for Peter Fillat Architects, headquartered in Baltimore, with offices in San Diego and Brazil. Her focus was on the hospitality, mixed use, and multifamily industries. Prior to PFA, Terry Anne spent 15 years at the Urban Land Institute’s global headquarters in Washington DC. In her many positions at ULI, Terry Anne was responsible for the global growth of the Institute’s 40,000 members worldwide. Terry Anne is the ULI Baltimore Membership Committee Chair, the ULI Baltimore Wavemaker Co-Chair, and a member of the ULI Management and the Advisory Committees. She is also a member of ICSC, NAIOP, CREW, HBAM, the Irish American Business Society and serves as a committee member of GEM (Girls Empowerment Mission).
    </div>
    <div class="my-3">
        <b>Buzz Hiken, Vice President</b>, comes to Residential Title & Escrow Company after spending 8 years at a national title company as Senior Vice President of National Sales, where he acquired extensive knowledge of the residential and commercial aspects of the title world, developed relationships with over 150 new clients throughout the country, and played an integral role in improving both company’s sales and reputation. Prior to entering the title field, Buzz spent 25 years in the radio business as the Director of Sales for several premier stations. Over the years, Buzz’s radio stations set numerous billing records, which are indicative of his commitment to superior client service. Among his charitable work, Buzz chaired the 2000 March of Dimes fundraising efforts and is a past board member of the Leukemia and Lymphoma Society. A married father of two children, Buzz enjoys playing golf and tennis in his spare time.
    </div>
    <div class="my-3">
        <b>Dawn Jones, Administrative Assistant/Receptionist</b>, joined Residential Title & Escrow in February 2017. She has 10 years of knowledge in the real estate industry. She also received her Master’s in Higher Education in 2015. Dawn and her husband, Alvin have three children. She enjoys spending time with her awesome grandchildren, reading, and hanging out with her best friends and family.
    </div>
    <div class="my-3">
        <b>Dawn Lawson, Senior Settlement Processor</b>, joins us with 16 years of experience in post-closing, processing, and settlements. She specializes in new construction and resale processing and handles the majority of our builder accounts. Dawn currently lives in Anne Arundel County and in her free time, loves to spend time with her husband and two kids.
    </div>
    <div class="my-3">
        <b>Andrew Miller, Account Executive</b>, joined Residential Title & Escrow in 2016, coming from a career in Consulting. Matthew is born and raised in Baltimore and enjoys seeing the daily developments and improvements to his city. He is an avid sports fan and enjoys spending quality time with his family.
    </div>
    <div class="my-3">
        <b>Jackie Nelson, Account Executive</b>, Coming from a lucrative career as a real estate agent, joined Residential Title & Escrow Company in 1999. After almost 20 years with Residential Title & Escrow Company a partnership was formed. Out of that partnership Essential Title Services, LLC was created. ETS is an African American, Female owned and operated title company. When not at workshops, I enjoy spending time with my husband of 32 years, shopping and grandsons.
    </div>
    <div class="my-3">
        <b>Anne Louise Perlow, Senior Executive Vice President</b>, serves as the operations manager, overseeing pre-settlement, process signing, post settlement and post closing departments. She also serves on the human resources committee for the company. Anne Louise holds her title license within the State of Maryland. She attended the University of Maryland, College Park and has been actively working in the title industry for over 20 years. Anne Louise is married and has four children. In her spare time she has a passion for photography.
    </div>
    <div class="my-3">
        <b>Bonnie P. Perlow, President</b>, received her Masters of Education degree from Johns Hopkins University in 1975, prior to starting her career as an educator in the Baltimore City school system. In 1990, after a successful five years in the real estate title industry, she applied her experience to the founding of Residential Title & Escrow Company. Bonnie lives in Baltimore County and spends as much time as possible with her children & grandchildren. She has a love for animals and art.
    </div>
    <div class="my-3">
        <b>Howard Perlow, Executive Vice President</b>, graduated from the University of Maryland, cum laude, with a B.S. in Accounting, and afterwards earned his J.D. from the University of Baltimore School of Law. As a realtor in general brokerage prior to joining Residential Title & Escrow, Howard accumulated practical experience in real estate which further enhances his wealth of knowledge in the title industry. His highly specialized expertise in the processes surrounding title, allows him to be a valuable asset to many of the Baltimore region’s largest development companies. His unique ability to work out the most complex title problems. Over the past 40 years at Residential Title & Escrow, he has been a driving force behind the company’s growth, success, and reputation as the area’s leader in commercial title work. Howard is involved with several professional organizations including Home Builders Association of Maryland nka Maryland Building Industry Association, NAIOP, and ICSC. He is the recipient of the HBAM Lifetime Achievement Award and Associate of the Year Award. He currently sits on the Boards of Levindale Nursing Home and The Cancer Institute at St. Joseph Medical Center. Howard is presently the Co-President of the Shaarei Tfiloh Congregation. He is a previous member of the Beth Tfiloh School and Synagogue Boards. Howard is active in fundraising for Cancer Centers and several other organizations.
    </div>
    <div class="my-3">
        <b>Robyn N. Perlow, Account Executive</b>, brings 17 years of experience to Residential Title & Escrow Company where she has been since 2000. She is responsible for overseeing numerous builder, lender and realtor accounts. She graduated from McDaniel College in 2000 with a double major in Sociology and Criminal Justice. Robyn grew up in the suburbs of Baltimore, and after living in Federal Hill in the city, has moved back to Pikesville. She served on the events committee for The Home Builders Association of Maryland (nka MBIA), has chaired HBAM’s Celebrity Chef Night for 4 years and is a member of the Family Business Youth of Baltimore Club. In her time away from the office, she enjoys reading, art, art history, traveling and spending time with her daughter.
    </div>
    <div class="my-3">
        <b>Tory Ricas </b>came to Residential Title in 1993 after working ten years as a Paralegal in the Real Estate and Title Departments of a local law firm. That experience has allowed her the flexibility to work in various Departments throughout the Company including in Marketing and Post Closing. She enjoys the variety of her work and is willing to assist as needed.
    </div>
    <div class="my-3">
        <b>Sherri Sauter, Post Closing Manager</b>, has spent the last 25 years in the title industry and joined Residential Title & Escrow Company in 2012. She is a dedicated and organized worker which truly helps in any Post Closing Department. Sherri was born and raised on a farm and currently lives on a working farm in Woodstock, MD with her husband and two kids and lots and lots of animals.
    </div>
    <div class="my-3">
        <b>Sheila Savage, Residential Marketing Assistant</b>, has spent 15 years in the real estate industry and providing administrative support in maintaining new and existing real estate transactions for our clients. Additionally, she’s involved in various special events projects and a team player whenever and wherever needed. A native of Baltimore, in her time away from the office she enjoys traveling, bowling, movies and spending quality time with family and friends.
    </div>
    <div class="my-3">
        <b>Jennifer A. Schwartz, Settlement Processor</b>, comes to us with more than 20 years of experience and has processed files in all 50 states and in Puerto Rico. She has an AA in general studies from CCBC, grew up in New Windsor, Carroll County and currently resides in Baltimore County. In her time away from the office, she enjoys playing with her animals, family, watching and attending Ravens games and anything Edgar Allen Poe.
    </div>
    <div class="my-3">
        <b>Chaya Shimanovich, Settlement Processor</b>, joined Residential Title & Escrow Company in 2018 and has over 5 years of experience in the industry. She graduated from Yeshiva University in 2006. Chaya specializes in processing Residential, Short Sale and REO purchases and residential refinances. She enjoys spending time with her fiancé, family and friends.
    </div>
    <div class="my-3">
        <b>Linda Sill, Settlement Coordinator</b>, has been with Residential Title & Escrow Company for 26 years and our settlement coordinator for 22 years. She graduated from the University of Baltimore in 1989 with a BA in English: Professional Writing. She works with our local and national abstractors and surveyors for all of our Commercial & Residential closings to ensure title work and surveys make it to our office in a timely manner; along with helping all of clients coordinate their settlement date, time and place. Linda says the best part of her job is being able to communicate with so many people and striving to guarantee the settlement process goes smoothly. Linda is a native Baltimorean and lives in Reisterstown. On her time off time, she enjoys shopping, her Book Club and enjoying time with family and friends.
    </div>
    <div class="my-3">
        <b>Alicia Small, Account Executive</b>, was born in Canton, OH and moved to Maryland in 2011. She holds a Bachelor of Arts degree from Wright State University, and has worked in the real estate industry for over 10 years, with most of her experience in new home sales. Alicia volunteers with a nonprofit organization that mentors teenage girls in Laurel, MD. She lives in Baltimore with her husband and enjoys spending time with her family, photography and creating natural hair YouTube videos.
    </div>
    <div class="my-3">
        <b>Robin Abney Spivey, Account Executive</b>, graduated from Brooklyn College with a BA in Africana Studies. She has 30 years of experience in Real Estate. Her experience includes managing a portfolio of 1,500 units of luxury high rise Condominiums Units, conducting Settlements, Refinances as well as Deed Transfers. Her passion is service, educating consumers about the importance of home ownership and, creating wealth with Real Estate. She is President-Elect of the Real Estate Brokers of Baltimore which, is the local chapter of the National Association of Real Estate Brokers, an Affiliate Member of Howard County Association of Realtors and serves on its Fair Housing Committee. Robin enjoys spending time with her husband, family, antiques, real estate, golf, art, theater, movies, museums and travelling.
    </div>
    <div class="my-3">
        <b>Kevin L. Thomas, Senior Settlement Processor</b>, graduated from University of Maryland Baltimore County in 2002. He majored in Political Science and minored in History. He has been the title industry since 2002. He has a vast knowledge of foreclosures and residential sales. He is a licensed settlement officer and a public notary. In his free time, he enjoys spending time with his wife and two kids.
    </div>
    <div class="my-3">
        <b>Christine “Chris” Tipton, Vice President</b>, is a Maryland Licensed Title Agent and has been in the title industry for 32 years and has been with Commercial Settlement Services, LLC since 2014. Chris came to Commercial Settlement Services with an array of title knowledge and processing expertise in both residential and commercial processing. Chris handles commercial closings for lending institutions, builders, developers and she maintains a great communication at all times with attorneys, paralegals and all parties involved in the commercial transaction process, she continuously keeps all parties “in the loop” during their closing process, keeping cool under pressure is one of the many qualities that makes Chris stand out as a commercial closer. Having closed several hundreds of transactions in her career, Chris has become very skilled in successfully handling difficult transactions throughout her 32 years in the title industry. Chris currently resides in Harford County and has been married for 32 years with two beautiful children and enjoys spending time with family and her grandson Jack most of all, all while you can still find her on any baseball field where a game may be in action, Chris is a huge fan.
    </div>
    <div class="my-3">
        <b>Christopher Tritch, Settlement Processor</b>, graduated from Goucher College in 2011 and joined Residential Title & Escrow Company in 2018. He is a Maryland licensed Title Producer and has experience processing refinances, residential transactions, commercial transactions, foreclosures, and new construction. In his free time, he enjoys rock climbing and travelling.
    </div>
    <div class="my-3">
        <b>Tamara “Tami” vonEiff, Senior Settlement Processor</b>, joined Residential Title & Escrow Company in 2013 and has over 16 years of experience in the industry. She is a Maryland Licensed Producer and has an expertise in Processing; foreclosures, Short Sales, REO’s, New Construction, Refinances & Reverse Mortgages. She currently lives in Parkville with her husband Phil and two sons.
    </div>
    <div class="my-3">
        <b>Reeshemah Williams, Settlement Officer</b>, joined Residential Title in July 2016 with over 13 years of experience as a Licensed Title Agent. As a former Realtor, Reeshemah brings a wealth of experience from the Title Industry where she serviced Builders, Real Estate Agents and Lenders. Customer Service is always her top priority, and she appreciates all facets of the closing process. Reeshemah, a native of Baltimore, resides in Cockeysville, MD with her husband Chris for over 18 years. A mother of four, Briana, Christian, Cameron and Aylsa; and a proud grandmother to Jordan. She enjoys reading, church activities and spending time with her family.
    </div>
</div>
@endsection
